
# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp


# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com:algdat/blatt-2-amf0.git

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - g++-6
            - clang-3.9
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env: COMPILER=clang++-3.9 GENERATE_DOC=true

script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER && make
  - ./build/runAllTests


# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
