
# Use new trusty images, should yield newer compilers and packages
sudo: required # todo: try with false
dist: trusty
language: cpp


# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: blatt-2-amf0
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxyconf # todo: doxyconf
    - GH_REPO_REF: github.com:algdat/blatt-2-amf0.git

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - g++-6
            - clang-3.9
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env: COMPILER=clang++-3.9
before_install:
  - sudo apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ../graphtool && make
  - ./graphtool


# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
#  - ./generateDocumentationAndDeploy.sh
